// src/ui/TextEntry.tsx
import { useEffect, useRef, useState, type KeyboardEvent, type ReactNode } from "react";
import { CircleAlert, Delete, Space, X } from "lucide-react";
import { TvButton, focusElement } from "./remote";
import { DialogBackdrop } from "./DialogBackdrop";
import { buttonClass } from "./primitives/Button";
import { FieldValue, PinBoxes } from "./primitives/Fields";
import { KeyLegend } from "./primitives/Keys";

/** The TV layout (remote, on-screen keyboard). Unset (unit tests) reads as TV, like RemoteRoot. */
export const isTvLayout = () =>
  typeof document === "undefined" || document.documentElement.dataset.layout !== "responsive";

const isBack = (event: KeyboardEvent) =>
  ["Escape", "BrowserBack"].includes(event.key) || event.keyCode === 10009 || event.keyCode === 461;
const consume = (event: KeyboardEvent) => {
  event.preventDefault();
  event.stopPropagation();
};

/**
 * Text entry for every flow that asks for one value (profile name, parent PIN,
 * addon URL, catalog filter, Live TV search).
 *   phone    bottom sheet: title, field (or PIN boxes), count / inline error, Done + Cancel
 *   desktop  centred 460 dialog with the × close disc (Esc)
 *   TV       text: full screen, field left, keyboard right (BACK deletes, ▶▶ is Done);
 *            PIN (secret): right panel with the PIN keypad (BACK cancels)
 * Screens: PhProfileName, TvProfileName, PhPin, DeskPin, TvPin, TvPinError, PhFilterText,
 * TvFilterText, PhAddonInstall, DeskAddonInstall, TvAddonInstall.
 */
export function TextEntry({
  title,
  initialValue = "",
  secret = false,
  onSubmit,
  onCancel,
  maxLength,
  showCount = false,
  hint,
  mono,
  description,
}: {
  title: string;
  initialValue?: string;
  /** Parent PIN: digits only, 4–8, drawn as boxes. */
  secret?: boolean;
  onSubmit: (value: string) => Promise<void>;
  onCancel: () => void;
  maxLength?: number;
  /** "5 / 64" under the field. */
  showCount?: boolean;
  /** TV helper line under the field ("Select to type with your remote…"). */
  hint?: ReactNode;
  /** Monospace value (addon manifest URL); defaults to titles that name a URL. */
  mono?: boolean;
  /** PIN copy under the title; defaults per platform (copy.md). */
  description?: string;
}) {
  const [value, setValue] = useState(initialValue),
    [error, setError] = useState(""),
    [pending, setPending] = useState(false),
    [lower, setLower] = useState(true),
    [inputFocused, setInputFocused] = useState(false);
  const [tv] = useState(isTvLayout);
  const input = useRef<HTMLInputElement>(null);
  const limit = maxLength ?? (secret ? 8 : 2048);
  const monospace = mono ?? /\burl\b/i.test(title);
  const update = (next: string) => {
    setValue((secret ? next.replace(/\D/g, "") : next).slice(0, limit));
    setError("");
  };
  const append = (text: string) => update(value + text);
  const removeLast = () => update(value.slice(0, -1));
  useEffect(() => {
    if (tv) focusElement("text-key-0");
    else input.current?.focus();
  }, []);
  const save = async () => {
    if (pending) return;
    setPending(true);
    setError("");
    try {
      await onSubmit(value);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Unable to save");
    } finally {
      setPending(false);
    }
  };
  const onKeyDown = (event: KeyboardEvent<HTMLElement>) => {
    if (isBack(event)) {
      consume(event);
      // TV text entry: BACK deletes (legend "BACK Delete"); an empty field closes.
      if (tv && !secret && value && event.key !== "Escape") removeLast();
      else onCancel();
      return;
    }
    if (tv && !secret && (event.key === "MediaFastForward" || event.keyCode === 417)) {
      consume(event);
      void save();
      return;
    }
    if (event.target instanceof HTMLInputElement) {
      if (event.key === "Enter") {
        consume(event);
        void save();
      }
      return;
    }
    if (event.key === "Backspace" || event.key === "Delete") {
      consume(event);
      removeLast();
    } else if (
      event.key.length === 1 &&
      !event.ctrlKey &&
      !event.metaKey &&
      (!secret || /^\d$/.test(event.key))
    ) {
      consume(event);
      append(event.key);
    }
  };

  const errorLine = error ? (
    <span className="vx-inline-error" role="alert">
      <CircleAlert aria-hidden="true" />
      {error}
    </span>
  ) : null;
  const doneLabel = pending ? "Saving…" : "Done";
  // The real input: typed into on phone / desktop (and by a connected keyboard or
  // automation on TV, where it lies transparent over the drawn field).
  const field = (
    <input
      ref={input}
      className={secret ? "vx-entry__pin-input" : tv ? "vx-entry__tv-input" : "vx-field__input"}
      aria-label={title}
      aria-invalid={error ? true : undefined}
      type={secret ? "password" : "text"}
      inputMode={secret ? "numeric" : undefined}
      value={value}
      placeholder={secret || tv ? undefined : title}
      onChange={(event) => update(event.target.value)}
      onFocus={() => setInputFocused(true)}
      onBlur={() => setInputFocused(false)}
      autoComplete="off"
      autoCapitalize={monospace ? "none" : undefined}
      spellCheck={false}
      maxLength={limit}
      tabIndex={tv ? -1 : undefined}
    />
  );
  const pin = secret ? (
    <div className="vx-entry__pin">
      <PinBoxes
        length={Math.min(8, Math.max(6, value.length + 1))}
        filled={value.length}
        active={!error && (tv || inputFocused) && value.length < limit}
        error={!!error}
        label={`Parent PIN, ${value.length} of 4 to 8 digits entered`}
      />
      {field}
    </div>
  ) : null;
  const count = showCount && !secret ? <span className="vx-entry__count">{value.length} / {limit}</span> : null;

  if (!tv)
    return (
      <DialogBackdrop onCancel={onCancel} className="vx-entry-layer">
        <section
          className={`vx-dialog vx-entry${secret ? " vx-entry--pin" : ""}`}
          role="dialog"
          aria-modal="true"
          aria-label={secret ? "Authorization" : "Text entry"}
          data-focus-scope="entry"
          onKeyDown={onKeyDown}
        >
          <button type="button" className="vx-dialog__grabber" aria-label="Close" onClick={onCancel}><span /></button>
          <div className="vx-dialog__header">
            <h2 className="vx-dialog__title">{title}</h2>
            <button type="button" className="vx-close" aria-label="Close" onClick={onCancel}>
              <X aria-hidden="true" strokeWidth={2.2} />
            </button>
          </div>
          {secret ? (
            <>
              <p className="vx-dialog__text">{description ?? "Enter the parent PIN to continue."}</p>
              {pin}
            </>
          ) : (
            <label className={`vx-field${error ? " vx-field--error" : ""}${monospace ? " vx-field--mono" : ""}`}>
              <span className="vx-sr-only">{title}</span>
              <span className="vx-field__control">{field}</span>
            </label>
          )}
          {count}
          {errorLine}
          <div className="vx-dialog__actions">
            <TvButton
              id="text-save"
              type="button"
              className={buttonClass({ kind: "primary", block: true, icon: pending })}
              aria-busy={pending || undefined}
             
              onActivate={() => void save()}
            >
              {pending && <span className="vx-spinner" aria-hidden="true" />}
              {doneLabel}
            </TvButton>
            <TvButton id="text-cancel" type="button" className={buttonClass({ block: true })} onActivate={onCancel}>
              Cancel
            </TvButton>
          </div>
        </section>
      </DialogBackdrop>
    );

  const actions = (
    <div className="vx-keyboard__actions">
      <TvButton id="text-save" className={buttonClass({})} aria-busy={pending || undefined} onActivate={() => void save()}>
        {doneLabel}
      </TvButton>
      <TvButton id="text-cancel" className={buttonClass({})} onActivate={onCancel}>
        Cancel
      </TvButton>
    </div>
  );

  if (secret)
    return (
      <DialogBackdrop onCancel={onCancel} className="vx-entry-layer">
        <section
          className="vx-dialog vx-entry vx-entry--pin"
          role="dialog"
          aria-modal="true"
          aria-label="Authorization"
          data-focus-scope="entry"
          onKeyDown={onKeyDown}
        >
          <div className="vx-dialog__header">
            <h2 className="vx-dialog__title">{title}</h2>
          </div>
          <p className="vx-dialog__text">{description ?? "Use your remote or a connected keyboard."}</p>
          <div className="vx-entry__pin-block">
            {pin}
            {errorLine}
          </div>
          <div className="vx-keyboard vx-keypad">
            <div className="vx-keyboard__keys">
              {"123456789".split("").map((digit, index) => (
                <TvButton id={`text-key-${index}`} key={digit} className="vx-key" onActivate={() => append(digit)}>
                  {digit}
                </TvButton>
              ))}
              <TvButton id="text-delete" className="vx-key" aria-label="Delete" onActivate={removeLast} onHold={() => update("")}>
                <Delete aria-hidden="true" />
              </TvButton>
              <TvButton id="text-key-9" className="vx-key" onActivate={() => append("0")}>
                0
              </TvButton>
              <span aria-hidden="true" />
            </div>
            {actions}
          </div>
        </section>
        <KeyLegend corner items={[{ key: "OK", label: "Select" }, { key: "BACK", label: "Cancel" }]} />
      </DialogBackdrop>
    );

  const keys = `${lower ? "abcdefghijklmnopqrstuvwxyz" : "ABCDEFGHIJKLMNOPQRSTUVWXYZ"}1234567890:/.-_@`;
  return (
    <DialogBackdrop onCancel={onCancel} className="vx-entry-layer vx-entry-layer--full">
      <section className="vx-tv-entry vx-entry" role="dialog" aria-modal="true" aria-label="Text entry" data-focus-scope="entry" onKeyDown={onKeyDown}>
        <div className="vx-tv-entry__main">
          <h2 className="vx-tv-entry__title">{title}</h2>
          <label className={`vx-field${error ? " vx-field--error" : ""}${monospace ? " vx-field--mono" : ""}`}>
            <span className="vx-sr-only">{title}</span>
            <span className="vx-field__control">
              <FieldValue value={secret ? "" : value} placeholder={title} caret />
              {field}
            </span>
          </label>
          {errorLine || hint || count ? (
            <div className="vx-tv-entry__hints">
              {errorLine ?? <span>{hint}</span>}
              {count && <span className="vx-tv-entry__count">{value.length} / {limit}</span>}
            </div>
          ) : null}
        </div>
        <div className="vx-tv-entry__keys">
          <div className="vx-keyboard">
            <div className="vx-keyboard__keys">
              {keys.split("").map((c, index) => (
                <TvButton id={`text-key-${index}`} key={index} className="vx-key" onActivate={() => append(c)}>
                  {c}
                </TvButton>
              ))}
              <TvButton id="text-case" className="vx-key vx-key--action" aria-label="Shift" aria-pressed={!lower} onActivate={() => setLower(!lower)}>
                Aa
              </TvButton>
              <TvButton id="text-space" className="vx-key vx-key--action vx-key--span-3" aria-label="Space" onActivate={() => append(" ")}>
                <Space aria-hidden="true" />
              </TvButton>
              <TvButton id="text-delete" className="vx-key vx-key--action vx-key--span-2" aria-label="Delete" onActivate={removeLast} onHold={() => update("")}>
                <Delete aria-hidden="true" />
              </TvButton>
            </div>
            {actions}
          </div>
        </div>
      </section>
      <KeyLegend corner items={[{ key: "OK", label: "Type" }, { key: "BACK", label: "Delete" }, { key: "▶▶", label: "Done" }]} />
    </DialogBackdrop>
  );
}

// src/tv-solid/TextEntry.tsx
/** @jsxImportSource @solidtv/solid */
import { For, createMemo, createSignal, onCleanup, onMount } from 'solid-js';
import { activeElement, type ElementNode } from '@solidtv/solid';
import { TvText, TvView } from './runtime';
import { canvasFont } from './fonts';
import { tokens } from '../theme/viptv-tokens.generated';
import { EntryButton, EntryLegend, restoreEntryFocus } from './EntryButton';

export interface TextEntryProps {
  title: string; initialValue?: string; secret?: boolean; onSubmit: (value: string, signal?: AbortSignal) => Promise<void>; onCancel: () => void;
  maxLength?: number; showCount?: boolean; hint?: string; mono?: boolean; description?: string;
}
export function TextEntry(props: TextEntryProps) {
  const [value, setValue] = createSignal(props.initialValue ?? ''), [error, setError] = createSignal(''), [pending, setPending] = createSignal(false), [lower, setLower] = createSignal(true);
  const nodes = new Map<string, ElementNode>(), opener = activeElement();
  let alive = true, root: ElementNode | undefined;
  let submission: AbortController | undefined;
  const cancel = () => { submission?.abort(); props.onCancel(); };
  const limit = props.maxLength ?? (props.secret ? 8 : 2048);
  const update = (next: string) => { if (pending()) return; setValue((props.secret ? next.replace(/\D/g, '') : next).slice(0, limit)); setError(''); };
  const append = (text: string) => update(value() + text);
  const remove = () => update(value().slice(0, -1));
  const focus = (id: string) => nodes.get(id)?.setFocus();
  onMount(() => focus('key-0'));
  onCleanup(() => { alive = false; submission?.abort(); restoreEntryFocus(root, opener); });
  const save = async () => {
    if (!alive || pending()) return;
    if (props.secret && !/^\d{4,8}$/.test(value())) { setError('Enter a 4–8 digit parent PIN'); return; }
    setPending(true); setError('');
    const request = new AbortController(); submission = request;
    try { await props.onSubmit(value(), request.signal); } catch (e) { if (alive && !request.signal.aborted) setError(e instanceof Error ? e.message : 'Unable to save'); } finally { if (alive && !request.signal.aborted) setPending(false); }
  };
  const back = (event: KeyboardEvent) => { if (!props.secret && value() && event.key !== 'Escape') remove(); else cancel(); return true; };
  const key = (event: KeyboardEvent) => {
    if (['Escape', 'BrowserBack', 'GoBack'].includes(event.key) || [10009,461].includes(event.keyCode)) return back(event);
    if (event.key === 'MediaFastForward' || event.keyCode === 417) { void save(); return true; }
    if (['Backspace','Delete'].includes(event.key)) { remove(); return true; }
    if (event.key.length === 1 && !event.ctrlKey && !event.metaKey && (!props.secret || /^\d$/.test(event.key))) { append(event.key); return true; }
    return true; // modal input never reaches the screen below it
  };
  const letters = 'abcdefghijklmnopqrstuvwxyz1234567890:/.-_@';
  const count = props.secret ? 11 : 45;
  const cols = props.secret ? 3 : 6;
  const move = (index: number, direction: string) => {
    if (direction === 'Down' && Math.floor(index / cols) >= Math.floor((count - 1) / cols)) return focus('save');
    // The last text row has spans 1/3/2, so navigate by its visual columns.
    if (!props.secret && direction === 'Down' && index >= 36 && index < 42) return focus(`key-${index === 36 ? 42 : index < 40 ? 43 : 44}`);
    if (!props.secret && direction === 'Up' && index >= 42) return focus(`key-${index === 42 ? 36 : index === 43 ? 38 : 40}`);
    let next = index + ({Left:-1,Right:1,Up:-cols,Down:cols}[direction] ?? 0);
    if (direction === 'Left' && index % cols === 0 || direction === 'Right' && index % cols === cols - 1) next = index;
    focus(`key-${Math.max(0,Math.min(count - 1,next))}`);
  };
  const textMeasure=document.createElement('canvas').getContext('2d')!;
  const caretX=createMemo(()=>{
    textMeasure.font=`38px ${canvasFont('Onest600',38)}`;
    return 30+Math.min(926,textMeasure.measureText(value()||props.title).width)+parseFloat(tokens['space.0.5']);
  });
  const keyX = props.secret ? 1164 : 1184, keyY = props.secret ? 300 : 94, width = props.secret ? 480 : 640;
  const h = props.secret ? 80 : 64, gap = props.secret ? 12 : 10, unit = (width - (cols - 1) * gap) / cols;
  return <TvView nodeRef={(node: ElementNode) => { root = node; }} w={1920} h={1080} color={props.secret ? tokens["color.scrim.tv-panel"] : tokens["color.bg"]} onBack={back} onKeyPress={key}>
    <TvView show={!!props.secret} x={1100} w={820} h={1080} color={tokens["color.surface.1"]} />
    <TvText x={props.secret ? 1164 : 96} y={props.secret ? 64 : 94} size={44} font="Bricolage700" maxwidth={props.secret ? 660 : 980} content={props.title} />
    <TvText show={!!props.secret} x={1164} y={140} size={24} content={props.description ?? 'Use your remote or a connected keyboard.'} />
    <TvView show={!props.secret} x={96} y={170} w={992} h={96} rounded={22} color={tokens["color.fill.tv-field"]}>
      <TvText x={30} y={27} size={38} font="Onest600" maxwidth={932} maxlines={1} content={value() || props.title} color={value() ? tokens["color.text.primary"] : tokens["color.text.tertiary"]} />
      <TvView x={caretX()} y={29} w={parseFloat(tokens["size.caret.tv-width"])} h={38} color={tokens["color.accent.default"]} />
    </TvView>
    <For each={props.secret ? Array.from({length:8}, (_,i)=>i) : []}>{i => <TvView show={i < Math.max(6,value().length + 1)} x={1164+i*80} y={202} w={68} h={80} rounded={18} color={error() ? tokens["color.status.danger-tv"] : tokens["color.line.hairline"]}>
      <TvView x={2} y={2} w={64} h={76} rounded={16} color={tokens["color.surface.1"]} />
      <TvView x={2} y={2} w={64} h={76} rounded={16} color={tokens["color.fill.tv-field"]} />
      <TvView show={i < value().length} x={25} y={31} w={18} h={18} rounded={9} color={tokens["color.text.primary"]} />
      <TvView show={!error() && i === value().length && value().length < limit} x={33} y={22} w={2} h={36} color={tokens["color.accent.default"]} />
    </TvView>}</For>
    <TvText x={props.secret ? 1164 : 96} y={props.secret ? 770 : 292} size={22} maxwidth={props.secret ? 660 : 980} content={error() || props.hint || ''} color={error() ? tokens["color.status.danger-tv"] : tokens["color.text.tertiary"]} />
    <TvText show={!!props.showCount && !props.secret} x={96} y={292} w={992} maxwidth={992} align="right" size={20} content={`${value().length} / ${limit}`} color={tokens["color.text.tertiary"]} />
    <For each={Array.from({length:count}, (_,i)=>i)}>{i => {
      const action = i >= 42, span = i === 43 ? 3 : i === 44 ? 2 : 1;
      const column = i === 44 ? 4 : i % cols;
      const label = () => props.secret ? i === 9 ? '⌫' : i === 10 ? '0' : String(i+1) : i === 42 ? 'Aa' : i === 43 ? 'Space' : i === 44 ? '⌫' : lower() ? letters[i] : letters[i].toUpperCase();
      const glyph = props.secret ? i===9 ? 'delete' : undefined : i===43 ? 'space' : i===44 ? 'delete' : undefined;
      return <EntryButton keyboard id={`key-${i}`} x={keyX+column*(unit+gap)} y={keyY+Math.floor(i/cols)*(h+gap)} w={unit*span+gap*(span-1)} h={h} radius={props.secret ? 18 : 14} label={glyph ? undefined : label()} keyGlyph={glyph} keyGlyphSize={props.secret ? 32 : 28} labelWeight={action ? 700 : 600} size={props.secret ? 34 : action ? 24 : 28}
        register={(id,node)=>nodes.set(id,node)} onMove={direction=>move(i,direction)} onActivate={()=>{ if (props.secret && i===9 || !props.secret && i===44) remove(); else if (!props.secret && i===42) setLower(!lower()); else append(!props.secret && i===43 ? ' ' : label()); }} onHold={props.secret && i===9 || !props.secret && i===44 ? ()=>update('') : undefined} />;
    }}</For>
    <For each={['save','cancel']}>{(id,index)=><EntryButton id={id} x={keyX+index()*(width+14)/2} y={keyY+Math.ceil(count/cols)*(h+gap)+6} w={(width-14)/2} label={id==='save' ? pending() ? 'Saving…' : 'Done' : 'Cancel'} register={(id,node)=>nodes.set(id,node)} onActivate={()=>{ if(id==='save') void save(); else cancel(); }} onMove={direction=>focus(direction==='Up' ? `key-${count-1}` : direction==='Left' ? 'save' : direction==='Right' ? 'cancel' : id)} />}</For>
    <EntryLegend items={props.secret ? [{key:'OK',label:'Select'},{key:'BACK',label:'Cancel'}] : [{key:'OK',label:'Type'},{key:'BACK',label:'Delete'},{key:'▶▶',label:'Done'}]} />
  </TvView>;
}
